redis:
  url: ${REDIS_URL}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DATABASE}

tgbot:
  token: ${BOT_TOKEN}

network:
  admin_rest: ${ADMIN_API_REST}
  admin_grpc: ${ADMIN_API_GRPC}
  player_rest: ${PLAYER_API_REST}
  player_grpc: ${PLAYER_API_GRPS}