database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  ssl_mode: ${DB_SSL_MODE}

service:
  grpc_port: ${SERVICE_GRPC_PORT}
  rest_port: ${SERVICE_REST_PORT}
  swagger_path: ${SWAGGER_PATH}

kafka:
  host: ${KAFKA_HOST}
  port: ${KAFKA_PORT}
  topic_name_add_quiz_results: ${KAFKA_TOPIC_ADD_QUIZ_RESULT}